version: '3.8'
services:
  grafana:
    image: grafana/grafana:12.3.0
    container_name: Grafana
    restart: unless-stopped
    environment:
    - TZ=${TZ}
    - HOST_OS=Unraid
    - HOST_HOSTNAME=JP-Dell
    - HOST_CONTAINERNAME=Grafana
    - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    - GF_INSTALL_PLUGINS=${GRAFANA_PLUGINS}
    - GF_USERS_ALLOW_SIGN_UP=false
    - GF_SERVER_ROOT_URL=https://grafana.azuleluna.xyz
    - GF_SECURITY_COOKIE_SECURE=true
    volumes:
    - ${OBSERVABILITY_PATH}/grafana:/var/lib/grafana
    ports:
    - 3006:3000
    labels:
    - kuma.grafana.type=http
    - kuma.grafana.url=http://Grafana:3000/api/health
    - kuma.grafana.name=Grafana
    - kuma.grafana.interval=60
    - kuma.grafana.accepted_statuscodes=200
    - kuma.grafana.tags=monitoring,visualization
    - net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/grafana-icon.png
    - net.unraid.docker.webui=http://[IP]:[PORT:3006]
    networks:
    - monitoring_net
    - db_net
    user: ${PUID}:${PGID}
networks:
  monitoring_net:
    external: true
  db_net:
    external: true
