
services:
  uptimekuma:
    image: louislam/uptime-kuma:2.0.2
    container_name: UptimeKuma
    restart: unless-stopped
    environment:
    - TZ=${TZ}
    - HOST_OS=Unraid
    - HOST_HOSTNAME=JP-Dell
    - HOST_CONTAINERNAME=UptimeKuma
    volumes:
    - ${OBSERVABILITY_PATH}/uptimekuma:/app/data
    ports:
    - 3002:3001
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M
    labels:
    - net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/uptimekuma-icon.png
    - net.unraid.docker.webui=http://[IP]:[PORT:3002]
    networks:
    - monitoring_net
  autokuma:
    image: ghcr.io/bigboot/autokuma:2.0
    container_name: AutoKuma
    restart: unless-stopped
    environment:
    - TZ=${TZ}
    - HOST_OS=Unraid
    - HOST_HOSTNAME=JP-Dell
    - HOST_CONTAINERNAME=AutoKuma
    - AUTOKUMA_UPTIME_KUMA_URL=http://UptimeKuma:3001
    labels:
    - net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/autokuma-icon.png
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
    - monitoring_net
    - db_net
    - internal_net
    - iot_net
    - teslamate_net
    depends_on:
    - uptimekuma
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
networks:
  monitoring_net:
    external: true
  db_net:
    external: true
  internal_net:
    external: true
  iot_net:
    external: true
  teslamate_net:
    external: true
