
services:
  actualserver:
    image: actualbudget/actual-server:25.12.0
    container_name: ActualServer
    restart: unless-stopped
    environment:
    - TZ=${TZ}
    - HOST_OS=Unraid
    - HOST_HOSTNAME=JP-Dell
    - HOST_CONTAINERNAME=ActualServer
    - ACTUAL_UPLOAD_FILE_SIZE_SYNC_MB=20
    - ACTUAL_UPLOAD_FILE_SIZE_IMPORT_MB=20
    volumes:
    - ${APPDATA_PATH}/actual-server:/data
    ports:
    - 5006:5006
    networks:
    - internal_net
    labels:
    - kuma.actualserver.type=http
    - kuma.actualserver.url=http://ActualServer:5006
    - kuma.actualserver.name=Actual Budget Server
    - kuma.actualserver.interval=60
    - kuma.actualserver.keyword=Actual
    - kuma.actualserver.tags=productivity,budget
    - net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/actualserver-icon.png
    - net.unraid.docker.webui=http://[IP]:[PORT:5006]
networks:
  internal_net:
    external: true
