config-version = "2.7"
bind = "0.0.0.0:25565"
motd = "AzuleLuna Network â€¢ Welcome!"
show-max-players = 200

online-mode = true
force-key-authentication = true

proxy-protocol = true
player-info-forwarding-mode = "modern"
forwarding-secret = "${CFG_FORWARDING_SECRET}"

servers = {
  hub = "mc-hub:25565",
  vanilla = "mc-vanilla:25565",
  ftb = "mc-ftb:25565"
}

try = ["hub"]
connection-throttle = 3000